services:
  db:
    extends:
      file: docker-compose.yml
      service: db

  fusionauth:
    extends:
      file: docker-compose.yml
      service: fusionauth

  fuseki:
    extends:
      file: docker-compose.yml
      service: fuseki

  scalatra:
    container_name: "scalatra"
    build:
      context: .
      dockerfile: Toxygates/Dockerfile
    depends_on:
      - fusionauth
      - fuseki
    networks:
      - panomicon_net
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      JVM_ARGS: ${SCALATRA_JVM_ARGS}
      PORT: 8888
      T_TS_URL: ${T_TS_URL}
      T_TS_UPDATE_URL: ${T_TS_UPDATE_URL}
      T_DATA_MATDBCONFIG: ${T_DATA_MATDBCONFIG}
      T_DATA_DIR: /data
      T_TS_USER: ${T_TS_USER}
      T_TS_PASS: ${T_TS_PASS}
      T_INSTANCE_NAME: ${T_INSTANCE_NAME}
      FUSIONAUTH_BASEURL: ${FUSIONAUTH_BASEURL}
      FUSIONAUTH_APP_URL: ${FUSIONAUTH_APP_URL}
      FUSIONAUTH_CLIENTID: ${FUSIONAUTH_CLIENTID}
      FUSIONAUTH_CLIENTSECRET: ${FUSIONAUTH_CLIENTSECRET}
      REDIRECT_AFTER_AUTH_URL: ${REDIRECT_AFTER_AUTH_URL}
      JWT_ISSUER: ${JWT_ISSUER}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      T_INTERMINE_NAME: ${T_INTERMINE_NAME}
      T_INTERMINE_ID: ${T_INTERMINE_ID}
      T_INTERMINE_URL: ${T_INTERMINE_URL}

    volumes:
      - ${T_DATA_DIR}:/data

  toxygates:
    container_name: "toxygates-gwt"
    build:
      context: .
      dockerfile: Toxygates/Dockerfile.gwt
    depends_on:
      - fuseki
    networks:
      - panomicon_net
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${T_DATA_DIR}:/data
    environment:
      JAVA_OPTS : "
        ${TOMCAT_JVM_ARGS} 
        -Dtoxygates.repositoryURL=${T_TS_URL} 
        -Dtoxygates.updateURL=${T_TS_UPDATE_URL}
        -Dtoxygates.instanceName=${T_INSTANCE_NAME}
        -Dtoxygates.repositoryUser=${T_TS_USER}
        -Dtoxygates.repositoryPassword=${T_TS_PASS}
        -Dtoxygates.dataDir=/data
        -Dtoxygates.csvDir=/usr/local/tomcat/webapps/toxygates/csv
        -Dtoxygates.cvsUrlBase=${T_CSV_URLBASE}
        -Dtoxygates.feedbackReceivers=jtnystrom@gmail.com
        -Dtoxygates.feedbackFromAddress=root@panomicon.nibn.go.jp
        -Dtoxygates.intermine.target.appname=${T_INTERMINE_NAME}
        -Dtoxygates.intermine.target.title=${T_INTERMINE_ID}
        -Dtoxygates.intermine.target.userurl=${T_INTERMINE_URL}
        "
  node:
     build:
       context: angular/ 
       dockerfile: "Dockerfile"
     depends_on:
       - scalatra
       - fusionauth
     ports:
       - "4200:80"
     tty: true
     restart: unless-stopped
     networks:
       - panomicon_net
     volumes:
       - ./angular/nginx/conf.d:/etc/nginx/conf.d

networks:
  panomicon_net:
    driver: bridge

volumes:
  fusionauth_db_data:
  fusionauth_config:

