package otg.model.sample;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import t.model.sample.Attribute;
import t.model.sample.CoreParameter;
import static otg.model.sample.Attribute.*;

public class AttributeSet extends t.model.sample.AttributeSet {
    public AttributeSet(Collection<Attribute> attributes, Collection<Attribute> required) {
    super(attributes, required);   
    Collections.addAll(previewDisplay, Dose, DoseUnit, DoseLevel,
        ExposureTime, AdmRoute);
    Collections.addAll(highLevel, Organism, Organ, TestType, Repeat);
  }
    
  private static AttributeSet defaultSet;

  synchronized public static AttributeSet getDefault() {
    if (defaultSet == null) {
      List<Attribute> attributes = new ArrayList<Attribute>();
      Collections.addAll(attributes, CoreParameter.values());
      Collections.addAll(attributes, otg.model.sample.Attribute.values());
      List<Attribute> required = new ArrayList<Attribute>();
      
      //TODO having CoreParameter.BatchGraph in required may pose problems for certain backend tools
      //e.g. manual insertion
      //Consider having an isAutoGenerated method on attributes.
      Collections.addAll(required, CoreParameter.values());
      Collections.addAll(required, Organism, TestType, Repeat, Organ,
        Compound, DoseLevel, ExposureTime);
      
      defaultSet = new AttributeSet(attributes, required);
    }
    return defaultSet;
  }
  
  private List<Attribute> previewDisplay = new ArrayList<Attribute>();  
  @Override
  public Collection<Attribute> getPreviewDisplay() { return previewDisplay; }
  
  private List<Attribute> highLevel = new ArrayList<Attribute>();  
  @Override
  public Collection<Attribute> getHighLevel() { return highLevel; }
  
}
